on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened]

name: CI
jobs:
  lint-python-code:
    if: "${{ !contains(github.event.commits[0].message, 'chore(release):') }}"
    uses: xoanmm/actions/.github/workflows/lint_python.yml@v0
    with:
      python-version: '3.8'

  unit-tests:
    if: "${{ !contains(github.event.commits[0].message, 'chore(release):') }}"
    needs:
      - lint-python-code
    uses: xoanmm/actions/.github/workflows/unit_tests_python.yml@v0
    with:
      python-version: '3.8'

  security-checks:
    if: "${{ !contains(github.event.commits[0].message, 'chore(release):') }}"
    needs:
      - unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact for coverage
        uses: actions/download-artifact@v4.1.7
        with:
          name: coverage

      - name: Get repository basename
        run: |
            echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v4.1.0
        with:
          args: >
            -Dsonar.projectKey=${{ github.repository_owner }}_${{ env.REPO_NAME }}
            -Dsonar.organization=${{ github.repository_owner }}
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.test.exclusions=tests/**
            -Dsonar.tests=tests/
            -Dsonar.verbose=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
