on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened]

name: CI
jobs:
  lint-python-code:
    if: "${{ !contains(github.event.commits[0].message, 'chore(release):') }}"
    uses: xoanmm/actions/.github/workflows/lint_python.yml@v0
    with:
      python-version: '3.12'
      requirements-files: 'requirements.txt requirements-tests.txt'

  unit-tests:
    if: "${{ !contains(github.event.commits[0].message, 'chore(release):') }}"
    needs:
      - lint-python-code
    uses: xoanmm/actions/.github/workflows/unit_tests_python.yml@v0
    with:
      python-version: '3.12'
      requirements-files: 'requirements.txt requirements-tests.txt'

  security-checks:
    if: "${{ !contains(github.event.commits[0].message, 'chore(release):') }}"
    needs:
      - unit-tests
    uses: xoanmm/actions/.github/workflows/sonar_cloud_scan_python.yml@v0
    secrets: inherit
