on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, synchronize, reopened]

name: CI
jobs:
  lint-python-code:
    if: "${{ !contains(github.event.commits[0].message, 'chore(release):') }}"
    uses: xoanmm/actions/.github/workflows/lint_python.yml@8fb1ad6e65f9792a66e3ab6e5060cf4503b1e610
    with:
      python-version: '3.13'
      requirements-files: 'requirements.txt requirements-tests.txt'

  unit-tests:
    if: "${{ !contains(github.event.commits[0].message, 'chore(release):') }}"
    needs:
      - lint-python-code
    uses: xoanmm/actions/.github/workflows/unit_tests_python.yml@8fb1ad6e65f9792a66e3ab6e5060cf4503b1e610
    with:
      python-version: '3.13'
      requirements-files: 'requirements.txt requirements-tests.txt'

  validate-dockerfile:
    # if: "${{ !contains(github.event.commits[0].message, 'chore(release):') }}"
    needs:
      - lint-python-code
      - unit-tests
    uses: xoanmm/actions/.github/workflows/validate_dockerfile.yml@8fb1ad6e65f9792a66e3ab6e5060cf4503b1e610

  security-checks:
    if: "${{ !contains(github.event.commits[0].message, 'chore(release):') }}"
    needs:
      - lint-python-code
      - validate-dockerfile
      - unit-tests
    uses: xoanmm/actions/.github/workflows/sonar_cloud_scan_python.yml@8fb1ad6e65f9792a66e3ab6e5060cf4503b1e610
    with:
      python-version: '3.13'
      sonar-qualitygate-wait: true
      artifact-coverage-directory: '.'
    secrets: inherit
