name: release-build

on:
  workflow_run:
    workflows:
      - "CI"
    branches: [ main ]
    types:
      - completed

permissions:
  contents: write
  packages: write
  pull-requests: read
  issues: write
  id-token: write
  attestations: write

jobs:
  semantic-release:
    uses: xoanmm/actions/.github/workflows/release.yml@v0
    secrets: inherit
    with:
      dockerfile: Dockerfile
      docker-context: .
